package fr.slickteam.mistralai.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a single choice or response in a streaming chat completion process.
 * Each instance of this class corresponds to a partial or complete response from
 * the model within a chat session, including relevant metadata about the response.
 */
public class ChatCompletionStreamChoice {

    /**
     * Identifies the sequential position of this particular chat completion response
     * within a stream of responses. This is useful for tracking and reassembling
     * responses when working with streamed or batched data.
     */
    private int index;

    /**
     * Represents the content of a single response or completion in a chat session.
     * This field contains the actual text output generated by the model as part
     * of the chat completion process.
     */
    private String text;

    /**
     * Represents the reason for the completion of a streaming chat response.
     * This variable indicates whether the response was finished naturally,
     * due to token limits, stopped by a user intervention, or for any other reason.
     * Common values might include "stop", "length", "content_filter", or others
     * depending on the response context.
     */
    @JsonProperty("finish_reason")
    private String finishReason;

    /**
     * Represents a delta or incremental update to a chat message within
     * a real-time streaming chat process. The `delta` typically contains
     * partial or new information provided by the model, including its role
     * and the associated content of the update.
     */
    private ChatMessageDelta delta;

    public ChatCompletionStreamChoice() {
    }

    public ChatCompletionStreamChoice(int index, String text, String finishReason, ChatMessageDelta delta) {
        this.index = index;
        this.text = text;
        this.finishReason = finishReason;
        this.delta = delta;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getFinishReason() {
        return finishReason;
    }

    public void setFinishReason(String finishReason) {
        this.finishReason = finishReason;
    }

    public ChatMessageDelta getDelta() {
        return delta;
    }

    public void setDelta(ChatMessageDelta delta) {
        this.delta = delta;
    }

    @Override
    public String toString() {
        return "ChatCompletionStreamChoice{" +
                "index=" + index +
                ", text='" + text + '\'' +
                ", finishReason='" + finishReason + '\'' +
                ", delta=" + delta +
                '}';
    }
}
