package fr.slickteam.mistralai.client.model;

import java.util.List;

/**
 * Represents a response from the chat completions endpoint of the Mistral AI API.
 * This class contains the generated completions and metadata about the request.
 */
public record ChatResponse(
    /**
     * The unique identifier for the chat completion.
     */
    String id,

    /**
     * The object type, typically "chat.completion".
     */
    String object,

    /**
     * The Unix timestamp (in seconds) of when the chat completion was created.
     */
    Long created,

    /**
     * The model used for the chat completion.
     */
    String model,

    /**
     * The list of completion choices generated by the model.
     */
    List<ChatChoice> choices,

    /**
     * Usage statistics for the request.
     */
    Usage usage
) {
    /**
     * Returns a new Builder instance to create a ChatResponse.
     *
     * @return a new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder class for creating ChatResponse instances.
     */
    public static class Builder {
        private String id;
        private String object;
        private Long created;
        private String model;
        private List<ChatChoice> choices;
        private Usage usage;

        /**
         * Sets the unique identifier for the chat completion.
         *
         * @param id the completion identifier
         * @return this builder instance
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Sets the object type.
         *
         * @param object the object type (typically "chat.completion")
         * @return this builder instance
         */
        public Builder object(String object) {
            this.object = object;
            return this;
        }

        /**
         * Sets the creation timestamp.
         *
         * @param created the Unix timestamp when the completion was created
         * @return this builder instance
         */
        public Builder created(Long created) {
            this.created = created;
            return this;
        }

        /**
         * Sets the model used for the chat completion.
         *
         * @param model the model identifier
         * @return this builder instance
         */
        public Builder model(String model) {
            this.model = model;
            return this;
        }

        /**
         * Sets the list of completion choices.
         *
         * @param choices the list of chat choices
         * @return this builder instance
         */
        public Builder choices(List<ChatChoice> choices) {
            this.choices = choices;
            return this;
        }

        /**
         * Sets the usage statistics.
         *
         * @param usage the usage statistics
         * @return this builder instance
         */
        public Builder usage(Usage usage) {
            this.usage = usage;
            return this;
        }

        /**
         * Builds a new ChatResponse instance with the current builder values.
         *
         * @return a new ChatResponse instance
         */
        public ChatResponse build() {
            return new ChatResponse(id, object, created, model, choices, usage);
        }
    }
}
