package fr.slickteam.mistralai.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import fr.slickteam.mistralai.client.model.ChatMessage;
import fr.slickteam.mistralai.client.model.Prediction;
import fr.slickteam.mistralai.client.model.ResponseFormat;
import fr.slickteam.mistralai.client.model.Tool;
import fr.slickteam.mistralai.client.type.MistralPromptMode;

import java.util.List;
import java.util.Map;

/**
 * Represents a request for generating chat completions using a specified model and configuration parameters.
 * <p>
 * This class encapsulates the necessary data required to initiate a chat completion process,
 * including the model identifier, conversation context (messages), and various fine-tuning parameters
 * such as the maximum number of tokens, randomness levels, and safety checks.
 * <p>
 * Fields:
 * - model: Specifies the unique identifier of the model to be used for generating chat completions.
 * - messages: The list of chat messages forming the conversation context. Each message contains details
 * such as role (e.g., system, user) and content.
 * - temperature: Controls the randomness of the response. Higher values increase randomness,
 * while lower values make the output more deterministic.
 * - maxTokens: Indicates the maximum number of tokens allowed in the response. This defines
 * the upper limit for the model's output length.
 * - topP: Enables nucleus sampling, determining the probability threshold for token selection
 * during response generation. Accepts values in the range [0, 1].
 * - randomSeed: An optional seed value for reproducibility of results. Using the same seed
 * ensures consistent output for identical inputs and configurations.
 * - stream: Specifies whether the response should be streamed back incrementally. If true,
 * the response is delivered in parts as it is generated.
 * - safePrompt: Determines whether the input prompt undergoes a safety validation check to
 * comply with safety and compliance standards.
 */
public class ChatCompletionRequest {

    /**
     * Specifies the unique identifier of the model to be used for generating chat completions.
     * This field determines the particular machine learning model or variant
     * upon which the completion request will be based.
     * <p>
     * The value of this field must correspond to a valid model identifier,
     * which could represent a pre-trained model available on the platform
     * or a custom fine-tuned model.
     * <p>
     * Proper configuration of the `model` field is essential to ensure the
     * output aligns with the intended behavior, capabilities, or domain
     * of the selected model.
     */
    private String model;

    /**
     * A list of chat messages that collectively form the conversation context.
     * Each message in the list contains attributes such as the role (e.g., system, user)
     * and the content of the message.
     * <p>
     * This field is essential for generating responses, as the sequence and content
     * of messages provide the context for the model to understand the conversation.
     */
    private List<ChatMessage> messages;

    /**
     * Controls the randomness of responses generated by the model.
     * <p>
     * A higher value (e.g., 1.0) increases the randomness, allowing for more diverse
     * and creative outputs, while a lower value (e.g., 0.0) makes the output more
     * focused and deterministic. Adjust this parameter to balance between
     * creativity and precision based on the application's requirements.
     * <p>
     * Accepts values in the range [0.0, 1.0].
     */
    private Double temperature;

    /**
     * Specifies the maximum number of tokens allowed in the response for a chat completion request.
     * This field defines the upper limit for the length of the tokenized output generated
     * by the language model. It helps control the verbosity of the response and ensures
     * that the output adheres to predefined constraints.
     */
    @JsonProperty("max_tokens")
    private Integer maxTokens;

    /**
     * The top-p parameter, also known as nucleus sampling, determines the probability
     * threshold used to select tokens during the decoding process. When generating a response,
     * the model considers the smallest set of tokens whose cumulative probability exceeds this value.
     * <p>
     * A low value (e.g., 0.1) results in more constrained and focused output as fewer tokens
     * are considered, while a higher value (e.g., close to 1.0) includes more token possibilities,
     * generating more varied outputs.
     * <p>
     * A value of 1.0 completely disables nucleus sampling, allowing the model to consider
     * all tokens in the probability distribution.
     */
    @JsonProperty("top_p")
    private Double topP;

    /**
     * An optional seed value used for controlling the randomness in result generation.
     * <p>
     * By providing a specific seed, the random number generation can be made deterministic,
     * enabling reproducibility of results for the same inputs and configurations. If not specified,
     * results may vary between runs due to the non-deterministic nature of randomization processes.
     */
    @JsonProperty("random_seed")
    private Integer randomSeed;

    /**
     * Specifies whether the response should be streamed incrementally.
     * If set to true, the response will be delivered in parts as it is generated,
     * allowing for real-time consumption. If false, the response will be delivered
     * in a single, complete output after processing.
     */
    private Boolean stream;

    /**
     * Indicates whether the input prompt undergoes a safety validation check to ensure compliance
     * with predefined safety and ethical standards.
     * <p>
     * If set to true, the prompt will be assessed for potentially unsafe or non-compliant content
     * before processing. This validation helps mitigate risks associated with generating harmful
     * or inappropriate outputs.
     */
    @JsonProperty("safe_prompt")
    private Boolean safePrompt;

    /**
     * Stop generation if this token is detected. Or if one of these tokens is detected when providing an array
     */
    private List<String> stop;

    /**
     * Format of the response from the chat
     */
    @JsonProperty("response_format")
    private ResponseFormat responseFormat;

    private List<Tool> tools;

    @JsonProperty("tool_choice")
    private Object toolChoice;

    @JsonProperty("presence_penalty")
    private Double presencePenalty;

    @JsonProperty("frequency_penalty")
    private Double frequencyPenalty;

    private Integer n;

    private Prediction prediction;

    @JsonProperty("parallel_tool_calls")
    private Boolean parallelToolCalls;

    @JsonProperty("prompt_mode")
    private MistralPromptMode promptMode;

    private Map<String, Object> metadata;

    public ChatCompletionRequest() {
    }

    public ChatCompletionRequest(String model, List<ChatMessage> messages, Double temperature, Integer maxTokens,
                                 Double topP, Integer randomSeed, Boolean stream, Boolean safePrompt,
                                 List<String> stop, ResponseFormat responseFormat) {
        this.model = model;
        this.messages = messages;
        this.temperature = temperature;
        this.maxTokens = maxTokens;
        this.topP = topP;
        this.randomSeed = randomSeed;
        this.stream = stream;
        this.safePrompt = safePrompt;
        this.stop = stop;
        this.responseFormat = responseFormat;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public List<ChatMessage> getMessages() {
        return messages;
    }

    public void setMessages(List<ChatMessage> messages) {
        this.messages = messages;
    }

    public Double getTemperature() {
        return temperature;
    }

    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    public Integer getMaxTokens() {
        return maxTokens;
    }

    public void setMaxTokens(Integer maxTokens) {
        this.maxTokens = maxTokens;
    }

    public Double getTopP() {
        return topP;
    }

    public void setTopP(Double topP) {
        this.topP = topP;
    }

    public Integer getRandomSeed() {
        return randomSeed;
    }

    public void setRandomSeed(Integer randomSeed) {
        this.randomSeed = randomSeed;
    }

    public Boolean getStream() {
        return stream;
    }

    public void setStream(Boolean stream) {
        this.stream = stream;
    }

    public Boolean getSafePrompt() {
        return safePrompt;
    }

    public void setSafePrompt(Boolean safePrompt) {
        this.safePrompt = safePrompt;
    }

    public List<String> getStop() {
        return stop;
    }

    public void setStop(List<String> stop) {
        this.stop = stop;
    }

    public ResponseFormat getResponseFormat() {
        return responseFormat;
    }

    public void setResponseFormat(ResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
    }

    public List<Tool> getTools() {
        return tools;
    }

    public void setTools(List<Tool> tools) {
        this.tools = tools;
    }

    public Object getToolChoice() {
        return toolChoice;
    }

    public void setToolChoice(Object toolChoice) {
        this.toolChoice = toolChoice;
    }

    public Double getPresencePenalty() {
        return presencePenalty;
    }

    public void setPresencePenalty(Double presencePenalty) {
        this.presencePenalty = presencePenalty;
    }

    public Double getFrequencyPenalty() {
        return frequencyPenalty;
    }

    public void setFrequencyPenalty(Double frequencyPenalty) {
        this.frequencyPenalty = frequencyPenalty;
    }

    public Integer getN() {
        return n;
    }

    public void setN(Integer n) {
        this.n = n;
    }

    public Prediction getPrediction() {
        return prediction;
    }

    public void setPrediction(Prediction prediction) {
        this.prediction = prediction;
    }

    public Boolean getParallelToolCalls() {
        return parallelToolCalls;
    }

    public void setParallelToolCalls(Boolean parallelToolCalls) {
        this.parallelToolCalls = parallelToolCalls;
    }

    public MistralPromptMode getPromptMode() {
        return promptMode;
    }

    public void setPromptMode(MistralPromptMode promptMode) {
        this.promptMode = promptMode;
    }

    public Map<String, Object> getMetadata() {
        return metadata;
    }

    public void setMetadata(Map<String, Object> metadata) {
        this.metadata = metadata;
    }

    @Override
    public String toString() {
        return "ChatCompletionRequest{" +
                "model='" + model + '\'' +
                ", messages=" + messages +
                ", temperature=" + temperature +
                ", maxTokens=" + maxTokens +
                ", topP=" + topP +
                ", randomSeed=" + randomSeed +
                ", stream=" + stream +
                ", safePrompt=" + safePrompt +
                ", stop=" + stop +
                ", responseFormat=" + responseFormat +
                ", tools=" + tools +
                ", toolChoice=" + toolChoice +
                ", presencePenalty=" + presencePenalty +
                ", frequencyPenalty=" + frequencyPenalty +
                ", n=" + n +
                ", prediction=" + prediction +
                ", parallelToolCalls=" + parallelToolCalls +
                ", promptMode=" + promptMode +
                ", metadata=" + metadata +
                '}';
    }

}
