package fr.slickteam.mistralai.client.model;

/**
 * Chat message.
 * <p>
 * Used in Mistral AI API operations.
 */


import com.fasterxml.jackson.annotation.JsonInclude;
import fr.slickteam.mistralai.client.model.ToolCall;

import java.util.List;

/**
 * Represents a message in a chat conversation with the Mistral AI API.
 * Each message has a role (e.g., "user", "assistant", "system", "tool") and content.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ChatMessage(
    /**
     * The role of the message sender.
     * Possible values include "user", "assistant", "system", and "tool".
     */
    String role,

    /**
     * The content of the message.
     */
    Object content,

    /**
     * The tool calls generated by the model (for assistant role).
     */
    List<ToolCall> tool_calls,

    /**
     * Whether the message is a prefix (for assistant role).
     */
    Boolean prefix,

    /**
     * The ID of the tool call this message is responding to (for tool role).
     */
    String tool_call_id,

    /**
     * The name of the tool (for tool role).
     */
    String name
) {
    /**
     * Returns a new Builder instance to create a ChatMessage.
     *
     * @return a new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder class for creating ChatMessage instances.
     */
    public static class Builder {
        private String role;
        private Object content;
        private List<ToolCall> tool_calls;
        private Boolean prefix;
        private String tool_call_id;
        private String name;

        /**
         * Sets the role of the message sender.
         *
         * @param role the role (e.g., "user", "assistant", "system", "tool")
         * @return this builder instance
         */
        public Builder role(String role) {
            this.role = role;
            return this;
        }

        /**
         * Sets the content of the message.
         *
         * @param content the message content
         * @return this builder instance
         */
        public Builder content(Object content) {
            this.content = content;
            return this;
        }

        /**
         * Sets the tool calls generated by the model.
         *
         * @param tool_calls the tool calls
         * @return this builder instance
         */
        public Builder tool_calls(List<ToolCall> tool_calls) {
            this.tool_calls = tool_calls;
            return this;
        }

        /**
         * Sets whether the message is a prefix.
         *
         * @param prefix whether it's a prefix
         * @return this builder instance
         */
        public Builder prefix(Boolean prefix) {
            this.prefix = prefix;
            return this;
        }

        /**
         * Sets the tool call ID.
         *
         * @param tool_call_id the tool call ID
         * @return this builder instance
         */
        public Builder tool_call_id(String tool_call_id) {
            this.tool_call_id = tool_call_id;
            return this;
        }

        /**
         * Sets the name of the tool.
         *
         * @param name the tool name
         * @return this builder instance
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Builds a new ChatMessage instance with the current builder values.
         *
         * @return a new ChatMessage instance
         */
        public ChatMessage build() {
            return new ChatMessage(role, content, tool_calls, prefix, tool_call_id, name);
        }
    }
}
