package fr.slickteam.mistralai.client.model;

import fr.slickteam.mistralai.client.type.FinishReason;

/**
 * Represents a choice in a chat completion response from the Mistral AI API.
 * Each choice contains an index, a message, and a finish reason.
 */
public record ChatChoice(
    /**
     * The index of this choice in the list of choices.
     */
    Integer index,

    /**
     * The message generated by the model for this choice.
     */
    ChatMessage message,

    /**
     * The reason why the model stopped generating text.
     */
    FinishReason finish_reason
) {
    /**
     * Returns a new Builder instance to create a ChatChoice.
     *
     * @return a new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder class for creating ChatChoice instances.
     */
    public static class Builder {
        private Integer index;
        private ChatMessage message;
        private FinishReason finish_reason;

        /**
         * Sets the index of this choice in the list of choices.
         *
         * @param index the choice index
         * @return this builder instance
         */
        public Builder index(Integer index) {
            this.index = index;
            return this;
        }

        /**
         * Sets the message generated by the model for this choice.
         *
         * @param message the generated message
         * @return this builder instance
         */
        public Builder message(ChatMessage message) {
            this.message = message;
            return this;
        }

        /**
         * Sets the reason why the model stopped generating text.
         *
         * @param finish_reason the finish reason
         * @return this builder instance
         */
        public Builder finish_reason(FinishReason finish_reason) {
            this.finish_reason = finish_reason;
            return this;
        }

        /**
         * Builds a new ChatChoice instance with the current builder values.
         *
         * @return a new ChatChoice instance
         */
        public ChatChoice build() {
            return new ChatChoice(index, message, finish_reason);
        }
    }
}
