package fr.slickteam.mistralai.client.model;

/**
 * Classification response.
 * <p>
 * Used in Mistral AI API operations.
 */


import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.util.List;

/**
 * Represents the response obtained after performing a classification operation.
 * This class encapsulates the metadata and results of the classification process.
 */
public class ClassificationResponse {

    /**
     * A unique identifier for the classification response.
     * This ID serves as a reference to associate the response with a specific
     * classification process or request, ensuring traceability and tracking of
     * operations in the system.
     */
    @JsonProperty("id")
    private String id;

    /**
     * Represents the model used in the classification process.
     * This field identifies the specific model that was used
     * for classifying or processing the provided data.
     * Typically, it corresponds to a predefined model identifier or name.
     */
    @JsonProperty("model")
    private String model;

    /**
     * List of classification results generated by a classification operation.
     * This field contains the outcomes of the classification process,
     * with each entry in the list representing a specific result.
     *
     * The results typically include metadata such as identified categories,
     * confidence scores, or other relevant details depending on the classification context.
     * All individual results are encapsulated as instances of the
     * {@link ClassificationResult} class.
     */
    @JsonProperty("results")
    private List<ClassificationResult> results;

    /**
     * Default constructor for Jackson deserialization
     */
    public ClassificationResponse() {
    }

    /**
     * Parses a JSON string into a ClassificationResponse using Jackson
     *
     * @param json The JSON string to parse
     * @return A ClassificationResponse object
     * @throws IOException If there's an error parsing the JSON
     */
    public static ClassificationResponse parseClassificationResponse(String json) throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        return objectMapper.readValue(json, ClassificationResponse.class);
    }

    // Getters and Setters

    /**
     * Gets the unique identifier for this classification response
     *
     * @return The response ID
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier for this classification response
     *
     * @param id The response ID
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the model used for classification
     *
     * @return The model identifier
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the model used for classification
     *
     * @param model The model identifier
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Gets the list of classification results
     *
     * @return The list of classification results
     */
    public List<ClassificationResult> getResults() {
        return results;
    }

    /**
     * Sets the list of classification results
     *
     * @param results The list of classification results
     */
    public void setResults(List<ClassificationResult> results) {
        this.results = results;
    }
}
