package fr.slickteam.mistralai.client.model;

import java.util.List;

/**
 * Represents a vector embedding generated by the Mistral AI API.
 * An embedding is a numerical representation of text that captures its semantic meaning.
 */
public record Embedding(
    /**
     * The index of this embedding in the list of embeddings.
     */
    Integer index,

    /**
     * The vector representation of the input text.
     * This is a list of floating-point numbers that represent the text in a high-dimensional space.
     */
    List<Double> embedding,

    /**
     * The object type, typically "embedding".
     */
    String object
) {
    /**
     * Returns a new Builder instance to create an Embedding.
     *
     * @return a new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder class for creating Embedding instances.
     */
    public static class Builder {
        private Integer index;
        private List<Double> embedding;
        private String object;

        /**
         * Sets the index of this embedding in the list of embeddings.
         *
         * @param index the embedding index
         * @return this builder instance
         */
        public Builder index(Integer index) {
            this.index = index;
            return this;
        }

        /**
         * Sets the vector representation of the input text.
         *
         * @param embedding the list of floating-point numbers representing the embedding vector
         * @return this builder instance
         */
        public Builder embedding(List<Double> embedding) {
            this.embedding = embedding;
            return this;
        }

        /**
         * Sets the object type.
         *
         * @param object the object type (typically "embedding")
         * @return this builder instance
         */
        public Builder object(String object) {
            this.object = object;
            return this;
        }

        /**
         * Builds a new Embedding instance with the current builder values.
         *
         * @return a new Embedding instance
         */
        public Embedding build() {
            return new Embedding(index, embedding, object);
        }
    }
}
