package fr.slickteam.mistralai.client.model;

/**
 * Represents a function call generated by the model.
 */
public record FunctionCall(
    /**
     * The name of the function to call.
     */
    String name,

    /**
     * The arguments to call the function with, as generated by the model in JSON format.
     */
    Object arguments
) {
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String name;
        private Object arguments;

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder arguments(Object arguments) {
            this.arguments = arguments;
            return this;
        }

        public FunctionCall build() {
            return new FunctionCall(name, arguments);
        }
    }
}
