package fr.slickteam.mistralai.client.model;

import fr.slickteam.mistralai.client.type.ToolTypes;

/**
 * Represents a tool call generated by the model.
 */
public record ToolCall(
    /**
     * The ID of the tool call.
     */
    String id,

    /**
     * The type of tool. Currently only "function" is supported.
     */
    ToolTypes type,

    /**
     * The function being called.
     */
    FunctionCall function,

    /**
     * The index of the tool call.
     */
    Integer index
) {
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String id;
        private ToolTypes type = ToolTypes.FUNCTION;
        private FunctionCall function;
        private Integer index = 0;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder type(ToolTypes type) {
            this.type = type;
            return this;
        }

        public Builder function(FunctionCall function) {
            this.function = function;
            return this;
        }

        public Builder index(Integer index) {
            this.index = index;
            return this;
        }

        public ToolCall build() {
            return new ToolCall(id, type, function, index);
        }
    }
}
