package fr.slickteam.mistralai.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a single choice from a chat completion response.
 * <p>
 * This class contains essential details about an individual choice
 * resulting from a chat-based AI model's completion process. Each choice
 * includes an index for identification, the message content within the
 * completion, and the reason the completion process concluded.
 */
public class ChatCompletionChoice {

    /**
     * Represents the position or sequence number of the completion choice within the
     * list of all choices generated by the chat completion operation.
     * <p>
     * This field is typically used to identify the specific choice and
     * maintain the ordering of multiple choices in a response.
     */
    private int index;

    /**
     * Represents the message content of a specific choice in a chat completion.
     * <p>
     * This variable holds a `ChatMessage` object that contains details of the
     * response generated by the chat completion process, including the role,
     * content, and optionally the name associated with the message.
     */
    private ChatMessageResponse message;

    /**
     * Indicates the reason why the completion process concluded.
     * <p>
     * This variable typically contains a descriptive string that provides
     * information about the outcome or termination condition of the completion
     * operation. Examples may include reasons such as "length", "stop", or
     * other indicators determined by the completion logic.
     */
    @JsonProperty("finish_reason")
    private String finishReason;

    private String logprobs;

    public ChatCompletionChoice() {
    }

    public ChatCompletionChoice(int index, ChatMessageResponse message, String finishReason, String logprobs) {
        this.index = index;
        this.message = message;
        this.finishReason = finishReason;
        this.logprobs = logprobs;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public ChatMessageResponse getMessage() {
        return message;
    }

    public void setMessage(ChatMessageResponse message) {
        this.message = message;
    }

    public String getFinishReason() {
        return finishReason;
    }

    public void setFinishReason(String finishReason) {
        this.finishReason = finishReason;
    }

    public String getLogprobs() {
        return logprobs;
    }

    public void setLogprobs(String logprobs) {
        this.logprobs = logprobs;
    }

    @Override
    public String toString() {
        return "ChatCompletionChoice{" +
                "index=" + index +
                ", message=" + message +
                ", finishReason='" + finishReason + '\'' +
                ", logprobs='" + logprobs + '\'' +
                '}';
    }
}
