package fr.slickteam.mistralai.client.models;

import java.util.List;

/**
 * Represents the response object for a chat completion operation.
 * <p>
 * This class encapsulates the details of a response generated by a
 * chat-based completion process. It includes metadata about the response,
 * choices returned by the completion operation, and token usage details.
 */
public class ChatCompletionResponse {

    /**
     * Represents the unique identifier for the chat completion response.
     * <p>
     * This field provides a unique string value that can be used to
     * distinguish this specific response from others. It helps in
     * tracking, comparing, or managing the responses generated by the
     * chat completion process.
     */
    private String id;

    /**
     * Represents the type of object within the context of the chat completion response.
     * This field typically indicates the nature of the resource or entity
     * being referenced or returned in the response.
     */
    private String object;

    /**
     * Represents the Unix timestamp indicating when the chat completion response
     * was created. This value is often used to track the response's generation
     * time and manage chronological data processing workflows.
     */
    private long created;

    /**
     * Identifier of the model used in the chat completion response.
     * Represents the specific model configuration or version utilized
     * to generate the response. This field is essential to trace
     * which model produced the output and understand its context or behavior.
     */
    private String model;

    /**
     * A list of choices resulting from a chat completion operation.
     * <p>
     * Each element in the list represents a single completion choice created by
     * a chat-based AI model. These choices typically include details such as the
     * message content, its index in the response, and the reason the completion
     * process concluded.
     * <p>
     * The `choices` variable holds the complete collection of these choices and is
     * used to determine the outcomes of the response generated by the model.
     */
    private List<ChatCompletionChoice> choices;

    /**
     * Represents the token usage information for a chat completion response.
     * <p>
     * This field provides details about the number of tokens consumed during
     * the processing of a prompt, the tokens used for generating the completion,
     * and their combined total.
     * <p>
     * It is useful for analyzing resource consumption and costs associated with
     * API interactions, allowing users to monitor and optimize token usage.
     * <p>
     * Fields within the `Usage` class:
     * - `promptTokens`: The number of tokens used in the input prompt.
     * - `completionTokens`: The number of tokens used in generating the completion.
     * - `totalTokens`: The total number of tokens used (sum of prompt and completion tokens).
     */
    private Usage usage;

    public ChatCompletionResponse() {
    }

    public ChatCompletionResponse(String id, String object, long created, String model, List<ChatCompletionChoice> choices, Usage usage) {
        this.id = id;
        this.object = object;
        this.created = created;
        this.model = model;
        this.choices = choices;
        this.usage = usage;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getObject() {
        return object;
    }

    public void setObject(String object) {
        this.object = object;
    }

    public long getCreated() {
        return created;
    }

    public void setCreated(long created) {
        this.created = created;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public List<ChatCompletionChoice> getChoices() {
        return choices;
    }

    public void setChoices(List<ChatCompletionChoice> choices) {
        this.choices = choices;
    }

    public Usage getUsage() {
        return usage;
    }

    public void setUsage(Usage usage) {
        this.usage = usage;
    }

    @Override
    public String toString() {
        return "ChatCompletionResponse{" +
                "id='" + id + '\'' +
                ", object='" + object + '\'' +
                ", created=" + created +
                ", model='" + model + '\'' +
                ", choices=" + choices +
                ", usage=" + usage +
                '}';
    }
}
