package fr.slickteam.mistralai.client.models;

import java.util.List;

/**
 * OCR response model containing the extracted text and text blocks.
 */
public class OCRResponse {

    /**
     * Represents a unique identifier for the OCR response.
     * This field is commonly used to track or reference a specific
     * response generated by the OCR process.
     */
    public String id;

    /**
     * Represents the identifier of the specific model used in an OCR operation.
     * This field typically specifies the name or version of the AI model that performs
     * text recognition. It helps in determining which pre-trained or fine-tuned model
     * is selected for processing the input data.
     */
    public String model;

    /**
     * Represents the complete textual content extracted by the OCR process.
     * This field contains the aggregated text identified across all blocks
     * in the OCR response.
     */
    public String text;

    /**
     * Represents a list of OCRBlock objects that define individual text blocks
     * extracted during an OCR operation.
     *
     * Each OCRBlock provides information about a specific block of textual
     * content, including its extracted text and associated bounding box
     * coordinates. This list holds all the blocks identified in a given
     * OCR process.
     */
    public List<OCRBlock> blocks;

}